In [4]:
import pandas as pd
import time
import csv
import re
comp=pd.read_csv('glycaninsilico.csv', header =None)
comp.head(5)

                 0         1
0  (0, 3, 2, 0, 0)  1149.601
1  (0, 3, 2, 0, 1)  1540.785
2  (0, 3, 2, 0, 2)  1931.970
3  (0, 3, 2, 0, 3)  2323.154
4  (0, 3, 2, 0, 4)  2714.338

In [5]:
type(comp)

pandas.core.frame.DataFrame

In [6]:
sortcomp = comp.sort_values(by=[1])
sortcomp.head(20)

                    0         1
0     (0, 3, 2, 0, 0)  1149.601
1575  (1, 3, 2, 0, 0)  1323.690
225   (0, 4, 2, 0, 0)  1353.701
25    (0, 3, 3, 0, 0)  1394.727
3150  (2, 3, 2, 0, 0)  1497.780
5     (0, 3, 2, 1, 0)  1510.775
1800  (1, 4, 2, 0, 0)  1527.790
1     (0, 3, 2, 0, 1)  1540.785
450   (0, 5, 2, 0, 0)  1557.801
1600  (1, 3, 3, 0, 0)  1568.817
250   (0, 4, 3, 0, 0)  1598.827
50    (0, 3, 4, 0, 0)  1639.854
4725  (3, 3, 2, 0, 0)  1671.869
1580  (1, 3, 2, 1, 0)  1684.864
3375  (2, 4, 2, 0, 0)  1701.879
1576  (1, 3, 2, 0, 1)  1714.875
230   (0, 4, 2, 1, 0)  1714.875
2025  (1, 5, 2, 0, 0)  1731.890
3175  (2, 3, 3, 0, 0)  1742.906
226   (0, 4, 2, 0, 1)  1744.885

In [24]:
#modified from programmiz
def binarycompositionsearch(array, x, low, high):
    # Repeat until the pointers low and high meet each other
    while low <= high:
        mid = low + (high - low)//2
        print(f"mid is {mid} now")
        print(f"value:{array[mid]-x}")
        if abs(array[mid])-x)<5:
            return mid
        elif array[mid] < x:
            print("mid<x")
            low = mid + 1
            print(f"now lower bound is {low} and it's {array[low]}")
        else:
            print("mid>x")
            high = mid - 1
            print(f"now higher bound is {high} and it's {array[high]}")
    return -1

array = sortcomp[1]
array1 = [3, 4, 5, 6, 7, 8, 9]
x = 1714

result = binarycompositionsearch(array, x, 0, len(array)-1)

if result != -1:
    print("Element is present at index " + str(result))
else:
    print("Not found")

mid is 4724 now
value:5978.82
mid>x
now higher bound is 4723 and it's 7301.636
mid is 2361 now
value:2316.026
mid>x
now higher bound is 2360 and it's 3638.842
mid is 1180 now
value:1307.5259999999998
mid>x
now higher bound is 1179 and it's 4225.09
mid is 589 now
value:3356.517
mid>x
now higher bound is 588 and it's 4679.332
mid is 294 now
value:2778.2110000000002
mid>x
now higher bound is 293 and it's 4101.027
mid is 146 now
value:2497.112
mid>x
now higher bound is 145 and it's 3819.927
mid is 72 now
value:2152.917
mid>x
now higher bound is 71 and it's 3475.733
mid is 35 now
value:403.0749999999998
mid>x
now higher bound is 34 and it's 3320.638
mid is 17 now
value:1301.491
mid>x
now higher bound is 16 and it's 2624.306
mid is 8 now
value:970.3270000000002
mid>x
now higher bound is 7 and it's 2293.143
mid is 3 now
value:609.154
mid>x
now higher bound is 2 and it's 1931.97
mid is 1 now
value:-173.21499999999992
mid<x
now lower bound is 2 and it's 1931.97
mid is 2 now
value:217.97000000000003
mid>x
now higher bound is 1 and it's 1540.785
Not found